version: '3.7'
services:
  configserver:
    image: ostock/configserver:latest
    ports:
       - "8071:8071"
    # environment:
      # ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  # eurekaserver:
    # image: ostock/eurekaserver:0.0.1-SNAPSHOT
    # ports:
      # - "8070:8070"
    # depends_on:
      # database:
        # condition: service_healthy
      # configserver:
        # condition: service_started  
    # networks:
      # backend:
        # aliases:
          # - "eurekaserver"
  licensingservice:
    image: ostock/licensing-service:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - configserver
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge